# Generated by Django 4.0.3 on 2022-04-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_project_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
