# Generated by Django 4.0.3 on 2022-05-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_social_github_profile_social_linkedin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_linkedin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_twitter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_website',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_youtube',
        ),
    ]
