# Generated by Django 4.0.1 on 2022-03-15 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_rename_tags_project_tagss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tagss',
            new_name='tags',
        ),
    ]
