# Generated by Django 4.0.3 on 2022-04-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
